[package]
name = "actix-web-example"
version = "0.3.0"
authors = ["Francesco Guardiani <francescoguard@gmail.com>"]
edition = "2018"

[dependencies]
cloudevents-sdk = { path = "../..", features = ["cloudevents-actix"] }
actix-web = "^3"
actix-cors = "^0.5"
lazy_static = "1.4.0"
bytes = "^0.5"
futures = "^0.3"
serde_json = "^1.0"
url = { version = "^2.1" }
env_logger = "0.7.1"

[workspace]